CREATE TABLE IF NOT EXISTS gym80_devices (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    category VARCHAR(50) NOT NULL,
    serie VARCHAR(100),
    model VARCHAR(255) NOT NULL,
    product_url TEXT,
    image_url TEXT,
    muscle_groups TEXT,
    notes TEXT
);



INSERT INTO gym80_devices (category, serie, model, product_url, image_url, muscle_groups, notes) VALUES
('plate_loaded', 'PURE KRAFT', '4023 45 DEGREE LINEAR LEG PRESS', 'https://gym80.de/en/product/plate-loaded-en/pure-kraft-en/4023-pure-kraft-45-degrees-linear-leg-press/', 'assets/gym80/4023.webp', 'Quadrizeps, Gesäß, Hamstrings', 'Plate Loaded'),
('plate_loaded', 'PURE KRAFT', '4038 SQUAT MACHINE', 'https://gym80.de/en/product/plate-loaded-en/pure-kraft-en/4038-pure-kraft-squat-machine/', 'assets/gym80/4038.webp', 'Quadrizeps, Gesäß, Hamstrings, Waden', 'Plate Loaded'),
('plate_loaded', 'PURE KRAFT', '4311 LAT PULLDOWN DUAL', 'https://gym80.de/en/product/plate-loaded-en/pure-kraft-en/4311-pure-kraft-lat-pulldown-dual/', 'assets/gym80/4311.webp', 'Latissimus, oberer Rücken, Bizeps', 'Plate Loaded'),
('plate_loaded', 'PURE KRAFT', '4314 SEATED LEG PRESS DUAL', 'https://gym80.de/en/product/plate-loaded-en/pure-kraft-en/4314-pure-kraft-beinpresse-sitzend-dual/', 'assets/gym80/4314.webp', 'Quadrizeps, Gesäß, Hamstrings', 'Plate Loaded'),
('plate_loaded', 'PURE KRAFT', '4318 BENT OVER ROW', 'https://gym80.de/en/product/plate-loaded-en/pure-kraft-en/4318-pure-kraft-bent-over-row/', 'assets/gym80/4318.webp', 'Rückenmitte, Latissimus, hintere Schulter, Bizeps', 'Plate Loaded'),
('plate_loaded', 'PURE KRAFT', '4319 LOW ROW DUAL', 'https://gym80.de/en/product/plate-loaded-en/pure-kraft-en/4319-pure-kraft-low-row/', 'assets/gym80/4319.webp', 'Latissimus, Rückenmitte, Bizeps', 'Plate Loaded'),
('plate_loaded', 'PURE KRAFT', '4320 SHOULDER PRESS DUAL', 'https://gym80.de/en/product/plate-loaded-en/pure-kraft-en/4320-pure-kraft-shoulder-press-dual/', 'https://gym80.de/wp-content/uploads/2020/02/gym80_4320_pure_kraft_schultermaschine_dual_overview.jpg', 'Schultern, Trizeps', 'Plate Loaded'),
('plate_loaded', 'PURE KRAFT', '4327 POWER ROW DUAL', 'https://gym80.de/en/product/plate-loaded-en/pure-kraft-en/4327-pure-kraft-power-row-dual/', 'assets/gym80/4327.webp', 'Rückenmitte, Latissimus, Bizeps, hintere Schulter', 'Plate Loaded'),
('plate_loaded', 'PURE KRAFT', '4335 TRICEPS DIP DUAL', 'https://gym80.de/en/product/plate-loaded-en/pure-kraft-en/4335-pure-kraft-triceps-dip-dual/', 'assets/gym80/4335.webp', 'Trizeps, Brust', 'Plate Loaded'),
('plate_loaded', 'PURE KRAFT', '4336N LEG EXTENSION', 'https://gym80.de/en/product/plate-loaded-en/pure-kraft-en/4336n-pure-kraft-leg-extension/', 'assets/gym80/4336n.webp', 'Quadrizeps', 'Plate Loaded'),
('plate_loaded', 'PURE KRAFT', '4337N LYING LEG CURL', 'https://gym80.de/en/product/plate-loaded-en/pure-kraft-en/4337n-pure-kraft-lying-leg-curl/', 'assets/gym80/4337n.webp', 'Hamstrings', 'Plate Loaded'),
('plate_loaded', 'PURE KRAFT', '4341 CHEST BUTTERFLY DUAL', 'https://gym80.de/en/product/plate-loaded-en/pure-kraft-en/4341-pure-kraft-chest-butterfly-dual/', 'https://gym80.de/wp-content/uploads/2020/02/gym80_4341_pure_kraft_butterfly_dual_overview-1.jpg', 'Brust, vordere Schulter', 'Plate Loaded'),
('plate_loaded', 'PURE KRAFT', '4344 BUTTERFLY REVERSE DUAL', 'https://gym80.de/en/product/plate-loaded-en/pure-kraft-en/4344-pure-kraft-butterfly-reverse-dual/', 'https://gym80.de/wp-content/uploads/2020/02/gym80_4344_pure_kraft_butterfly_reverse_dual_overview.jpg', 'hintere Schulter, oberer Rücken', 'Plate Loaded'),
('plate_loaded', 'PURE KRAFT', '4345 55 DEGREES STANDING CALF RAISE', 'https://gym80.de/en/product/plate-loaded-en/pure-kraft-en/4345-pure-kraft-55-degrees-standing-calf-raise/', 'https://gym80.de/wp-content/uploads/2020/02/gym80_4345_pure_kraft_55_grad_wadenmaschine_overview.jpg', 'Waden', 'Plate Loaded'),
('plate_loaded', 'PURE KRAFT', '4373 STANDING LEG CURL', 'https://gym80.de/en/product/plate-loaded-en/pure-kraft-en/4373-pure-kraft-standing-leg-curl/', 'https://gym80.de/wp-content/uploads/2023/08/gym80_4373_beinbeuger_stehend_overview.jpg', 'Hamstrings', 'Plate Loaded'),
('plate_loaded', 'PURE KRAFT', '4374 STANDING ABDUCTION', 'https://gym80.de/en/product/plate-loaded-en/pure-kraft-en/4374-pure-kraft-standing-abduction/', 'assets/gym80/4374.webp', 'Abduktoren, Gesäß', 'Plate Loaded'),
('plate_loaded', 'PURE KRAFT-STRONG', '4361 LEG PRESS DUAL', 'https://gym80.de/en/product/plate-loaded-en/pure-kraft-strong-en/4361-pure-kraft-beinpresse/', 'https://gym80.de/wp-content/uploads/2020/02/gym80_4361_pure_kraft_strong_beinpresse_overview-.jpg', 'Quadrizeps, Gesäß, Hamstrings', 'Plate Loaded'),
('plate_loaded', 'PURE KRAFT-STRONG', '4362 DECLINE BENCH PRESS DUAL', 'https://gym80.de/en/product/plate-loaded-en/pure-kraft-strong-en/4362-pure-kraft-strong-decline-bench-press-dual/', 'https://gym80.de/wp-content/uploads/2020/02/gym80_4362_pure_kraft_strong_negativdrueckbank_overview-1.jpg', 'untere Brust, Trizeps, vordere Schulter', 'Plate Loaded'),
('plate_loaded', 'PURE KRAFT-STRONG', '4363 SHOULDER PRESS DUAL', 'https://gym80.de/en/product/plate-loaded-en/pure-kraft-strong-en/4363-pure-kraft-strong-shoulder-press-dual/', 'assets/gym80/4363.webp', 'Schultern, Trizeps', 'Plate Loaded'),
('plate_loaded', 'PURE KRAFT-STRONG', '4364 BENCH PRESS DUAL', 'https://gym80.de/en/product/plate-loaded-en/pure-kraft-strong-en/4364-pure-kraft-strong-bench-press-dual/', 'assets/gym80/4364.webp', 'Brust, Trizeps, vordere Schulter', 'Plate Loaded'),
('plate_loaded', 'PURE KRAFT-STRONG', '4365 INCLINE BENCH PRESS DUAL', 'https://gym80.de/en/product/plate-loaded-en/pure-kraft-strong-en/4365-pure-kraft-strong-incline-chest-press-dual/', 'assets/gym80/4365.webp', 'obere Brust, Trizeps, vordere Schulter', 'Plate Loaded'),
('weight_stack', 'SYGNUM', '3001 LEG EXTENSION', 'https://gym80.de/produkt/3001/', 'assets/gym80/3001.webp', 'Quadrizeps', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3002 LYING LEG CURL', 'https://gym80.de/produkt/3002/', 'assets/gym80/3002.webp', 'Hamstrings', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3003 SEATED LEG CURL', 'https://gym80.de/produkt/3003/', 'assets/gym80/3003.webp', 'Hamstrings', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3004 KNEELING GLUTES KICK', 'https://gym80.de/produkt/3004/', 'assets/gym80/3004.webp', 'Gesäß', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3005 GLUTEUS KICK RADIAL', 'https://gym80.de/produkt/3005/', 'assets/gym80/3005.webp', 'Gesäß', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3006 TOTAL HIP MACHINE', 'https://gym80.de/produkt/3006/', 'assets/gym80/3006.webp', 'Gesäß, Hüfte, Beinmuskulatur', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3007 LOWER BACK MACHINE', 'https://gym80.de/produkt/3007/', 'assets/gym80/3007.webp', 'unterer Rücken', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3008 ABDOMINAL MACHINE', 'https://gym80.de/produkt/3008/', 'assets/gym80/3008.webp', 'Bauchmuskeln', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3010 BICEPS MACHINE', 'https://gym80.de/produkt/3010/', 'assets/gym80/3010.webp', 'Bizeps', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3011 TRICEPS EXTENSION', 'https://gym80.de/produkt/3011/', 'assets/gym80/3011.webp', 'Trizeps', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3012 PULL OVER MACHINE', 'https://gym80.de/produkt/3012n/', 'assets/gym80/3012n.webp', 'Latissimus, Brust, Serratus', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3013 STANDING LEG CURL', 'https://gym80.de/produkt/3013/', 'assets/gym80/3013.webp', 'Hamstrings', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3014 CHEST CROSSOVER MACHINE', 'https://gym80.de/produkt/3014/', 'https://gym80.de/wp-content/uploads/2020/06/gym80_5014_butterfly_butterfly_reverse_combo_overview-.jpg', 'Brust, vordere Schulter', 'SYGNUM COMBO'),
('weight_stack', 'SYGNUM', '3016 SEATED CHEST PRESS', 'https://gym80.de/produkt/3016/', 'assets/gym80/3016.webp', 'Brust, Trizeps, vordere Schulter', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3017 KNEELING / CHINNING-DIPPING MACHINE', 'https://gym80.de/produkt/3017/', 'assets/gym80/3017.webp', 'Latissimus, Bizeps, Brust, Trizeps', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3018 STANDING CALF RAISE MACHINE', 'https://gym80.de/en/product/weight-stack-en/sygnum-en/3018-standing-calf-raise-machine/', 'assets/gym80/3018.webp', 'Waden', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3020 LAT PULLDOWN MACHINE', 'https://gym80.de/en/product/weight-stack-en/sygnum-en/3020-lat-pulldown-machine/', 'https://gym80.de/wp-content/uploads/2020/01/gym80_3020_rueckenzugmaschine_front-2.jpg', 'Latissimus, oberer Rücken, Bizeps', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3021 BUTTERFLY WITH PADS', 'https://gym80.de/produkt/3021/', 'assets/gym80/3021.webp', 'Brust, vordere Schulter', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3022 BUTTERFLY', 'https://gym80.de/produkt/3022/', 'assets/gym80/3022.webp', 'Brust, vordere Schulter', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3023 INCLINE CHEST PRESS', 'https://gym80.de/produkt/3023n/', 'assets/gym80/3023n.webp', 'obere Brust, Trizeps, vordere Schulter', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3025 BUTTERFLY REVERSE', 'https://gym80.de/produkt/3025/', 'assets/gym80/3025.webp', 'hintere Schulter, oberer Rücken', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3027 SEATED CALF PRESS', 'https://gym80.de/produkt/3027/', 'assets/gym80/3027.webp', 'Waden', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3028 ABDUCTION MACHINE', 'https://gym80.de/produkt/3028/', 'assets/gym80/3028.webp', 'Abduktoren, Gesäß', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3029 ADDUCTION MACHINE', 'https://gym80.de/produkt/3029/', 'assets/gym80/3029.webp', 'Adduktoren', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3030 SEATED LEG PRESS', 'https://gym80.de/produkt/3030/', 'assets/gym80/3030.webp', 'Quadrizeps, Gesäß, Hamstrings', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3031 LYING LEG PRESS', 'https://gym80.de/en/product/weight-stack-en/sygnum-en/3031-lying-leg-press/', 'assets/gym80/3031.webp', 'Quadrizeps, Gesäß, Hamstrings', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3032 SHOULDER PRESS', 'https://gym80.de/en/product/weight-stack-en/sygnum-en/3032-shoulder-press/', 'assets/gym80/3032.webp', 'Schultern, Trizeps', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3034 LYING ABDOMINAL MACHINE', 'https://gym80.de/produkt/3034/', 'assets/gym80/3034.webp', 'Bauchmuskeln', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3036 DIP MACHINE', 'https://gym80.de/produkt/3036/', 'assets/gym80/3036.webp', 'Trizeps, Brust', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3037 ABDOMINAL MACHINE', 'https://gym80.de/produkt/3037/', 'assets/gym80/3037.webp', 'Bauchmuskeln', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3038 LOWER BACK MACHINE', 'https://gym80.de/produkt/3038/', 'assets/gym80/3038.webp', 'unterer Rücken', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3039 SEATED ROW WITHOUT CHEST SUPPORT', 'https://gym80.de/produkt/3039/', 'assets/gym80/3039.webp', 'Rückenmitte, Latissimus, Bizeps', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3040 SEATED ROW MACHINE', 'https://gym80.de/produkt/3040/', 'assets/gym80/3040.webp', 'Rückenmitte, Latissimus, Bizeps', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3041 DUAL CHEST PRESS', 'https://gym80.de/produkt/3041/', 'assets/gym80/3041.webp', 'Brust, Trizeps, vordere Schulter', 'SYGNUM DUAL'),
('weight_stack', 'SYGNUM', '3046 DUAL LEG PRESS', 'https://gym80.de/produkt/3046/', 'assets/gym80/3046.webp', 'Quadrizeps, Gesäß, Hamstrings', 'SYGNUM DUAL'),
('weight_stack', 'SYGNUM', '3047 ISO LAT', 'https://gym80.de/produkt/3047/', 'assets/gym80/3047.webp', 'Latissimus, Rückenmitte, Bizeps', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3050 SHOULDER LATERAL RAISE WITH GRIPS', 'https://gym80.de/produkt/3050/', 'assets/gym80/3050.webp', 'seitliche Schultern', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3069 STANDING ABDUCTION', 'https://gym80.de/produkt/3069/', 'assets/gym80/3069.webp', 'Abduktoren, Gesäß', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3071 FOREARMS MACHINE', 'https://gym80.de/produkt/3071/', 'assets/gym80/3071.webp', 'Unterarme', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3094 DONKEY CALF RAISE', 'https://gym80.de/produkt/3094/', 'assets/gym80/3094.webp', 'Waden', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3095 TRICEPS OVERHEAD', 'https://gym80.de/en/product/weight-stack-en/sygnum-en/3095-triceps-overhead/', 'assets/gym80/3095.webp', 'Trizeps', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3096 NECK PRESS', 'https://gym80.de/produkt/3096/', 'assets/gym80/3096.webp', 'Nacken, Schultern', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3097 INNER CHEST PRESS', 'https://gym80.de/produkt/3097/', 'assets/gym80/3097.webp', 'Brust, Trizeps, vordere Schulter', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3098 BICEPS HORIZONTAL', 'https://gym80.de/produkt/3098/', 'assets/gym80/3098.webp', 'Bizeps', 'SYGNUM'),
('weight_stack', 'SYGNUM', '3225 TWISTER MACHINE', 'https://gym80.de/produkt/3225/', 'assets/gym80/3225.webp', 'Core, schräge Bauchmuskeln', 'SYGNUM'),
('weight_stack', 'SYGNUM', '4004 CABLE CROSSOVER STATION', 'https://gym80.de/produkt/4004/', 'assets/gym80/4004.webp', 'Brust, Schultern, Core', 'SYGNUM'),
('weight_stack', 'SYGNUM', '4012 ADJUSTABLE CABLE CROSSOVER STATION', 'https://gym80.de/wp-content/uploads/2024/08/4034_DualAdjustablePulley_EN.pdf', 'assets/gym80/4012.webp', 'Brust, Schultern, Core', 'SYGNUM'),
('weight_stack', 'SYGNUM', '4016 ROWING STATION', 'https://gym80.de/en/product/weight-stack-en/sygnum-stations-en/4016-rowing-station/', 'assets/gym80/4016.webp', 'Rückenmitte, Latissimus, Bizeps', 'SYGNUM STATIONS'),
('weight_stack', 'SYGNUM', '4033 DUPLEX STATION', 'https://gym80.de/en/product/weight-stack-en/sygnum-stations-en/4033-duplex-station/', 'assets/gym80/4033.webp', 'Ganzkörper, funktionelles Training', 'SYGNUM STATIONS'),
('weight_stack', 'SYGNUM', '4034 DUAL ADJUSTABLE PULLEY', 'https://gym80.de/produkt/weight-stack/sygnum-stations/4034-dual-verstellbarer-seilzug/', 'assets/gym80/4034.webp', 'Ganzkörper, funktionelles Training', 'SYGNUM STATIONS'),
('weight_stack', 'SYGNUM', '4117 5 STATION TOWER', 'https://gym80.de/en/product/weight-stack-en/sygnum-stations-en/4117-5-station-tower/', 'assets/gym80/4117.webp', 'Ganzkörper, funktionelles Training', 'SYGNUM STATIONS'),
('weight_stack', 'SYGNUM', '4170 8 STATION TOWER', 'https://gym80.de/en/product/weight-stack-en/sygnum-stations-en/4170-8-station-tower/', 'assets/gym80/4170.webp', 'Ganzkörper, funktionelles Training', 'SYGNUM STATIONS'),
('weight_stack', 'SYGNUM', '5001 INNOVATION LEG PRESS', 'https://gym80.de/en/product/weight-stack-en/sygnum-en/5001-innovation-leg-press/', 'assets/gym80/5001.webp', 'Quadrizeps, Gesäß, Hamstrings', 'SYGNUM'),
('weight_stack', 'SYGNUM', '5101 CABLE ART - SHOULDER & BACK', 'https://gym80.de/produkt/5101/', 'assets/gym80/5101.webp', 'Schultern, Rücken', 'SYGNUM CABLE ART'),
('weight_stack', 'SYGNUM', '5102 CABLE ART - LAT & TRAPEZIUS', 'https://gym80.de/produkt/5102/', 'assets/gym80/5102.webp', 'Latissimus, Trapez', 'SYGNUM CABLE ART'),
('weight_stack', 'SYGNUM', '5103 CABLE ART - CHEST & SHOULDER', 'https://gym80.de/produkt/5103/', 'assets/gym80/5103.webp', 'Brust, Schultern', 'SYGNUM CABLE ART'),
('weight_stack', 'SYGNUM', '5104 CABLE ART', 'https://gym80.de/produkt/5104/', 'assets/gym80/5104.webp', 'Ganzkörper', 'SYGNUM CABLE ART'),
('weight_stack', 'SYGNUM', '5105 CABLE ART - UPPER BODY', 'https://gym80.de/produkt/5105/', 'assets/gym80/5105.webp', 'Oberkörper', 'SYGNUM CABLE ART'),
('weight_stack', 'SYGNUM', '5106 CABLE ART - LEGS', 'https://gym80.de/produkt/5106/', 'assets/gym80/5106.webp', 'Beine', 'SYGNUM CABLE ART'),
('weight_stack', 'SYGNUM', '5201 MULTI-POWER STATION', 'https://gym80.de/en/product/weight-stack-en/sygnum-stations-en/5201-multi-power-station/', 'assets/gym80/5201.webp', 'Ganzkörper, funktionelles Training', 'SYGNUM STATIONS'),
('weight_stack', 'SYGNUM', '5242 MULTI-POWER STATION PRIVATEGYM', 'https://gym80.de/en/product/weight-stack-en/sygnum-stations-en/5242-multi-power-station-privategym/', 'assets/gym80/5242.webp', 'Ganzkörper, funktionelles Training', 'SYGNUM STATIONS');
